/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CernicaAmbulanceWlList {
    }
}
declare global {
    interface HTMLCernicaAmbulanceWlListElement extends Components.CernicaAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLCernicaAmbulanceWlListElement: {
        prototype: HTMLCernicaAmbulanceWlListElement;
        new (): HTMLCernicaAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cernica-ambulance-wl-list": HTMLCernicaAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface CernicaAmbulanceWlList {
    }
    interface IntrinsicElements {
        "cernica-ambulance-wl-list": CernicaAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cernica-ambulance-wl-list": LocalJSX.CernicaAmbulanceWlList & JSXBase.HTMLAttributes<HTMLCernicaAmbulanceWlListElement>;
        }
    }
}
